"""
db_schema.py
Definição física do esquema do banco de dados SQLite para o projeto REDS-DM1.
Segue os nomes físicos, tipos e obrigatoriedades especificados no dicionário de dados REDS.
"""

import sqlite3

DDL_STATEMENTS = [
    # 1. SISTEMA_ORIGEM
    """
    CREATE TABLE IF NOT EXISTS SISTEMA_ORIGEM (
        IN_SISTEM_ORIGEM INTEGER PRIMARY KEY AUTOINCREMENT,
        NOME TEXT NOT NULL,
        LABEL TEXT
    );
    """,
    
    # 2. UNIDADE
    """
    CREATE TABLE IF NOT EXISTS UNIDADE (
        ID_UNID INTEGER PRIMARY KEY AUTOINCREMENT,
        CD_CNES TEXT UNIQUE NOT NULL,
        NM_UNID TEXT NOT NULL,
        DT_ATUALZ TEXT,
        CNPJ_RESPONSAVEL TEXT,
        TP_UNID INTEGER
    );
    """,
    
    # 3. PROFISSIONAL
    """
    CREATE TABLE IF NOT EXISTS PROFISSIONAL (
        ID_PROFIS INTEGER PRIMARY KEY AUTOINCREMENT,
        NM_PROFIS TEXT NOT NULL,
        CD_CPF TEXT UNIQUE NOT NULL,
        IN_SISTEM_ORIGEM INTEGER,
        FL_ANONIMIZADO TEXT DEFAULT '0',
        ID_SISTEM_ORIGEM INTEGER,
        DT_ATUALZ TEXT,
        FOREIGN KEY (IN_SISTEM_ORIGEM) REFERENCES SISTEMA_ORIGEM (IN_SISTEM_ORIGEM)
    );
    """,
    
    # 4. PROCEDIMENTO
    """
    CREATE TABLE IF NOT EXISTS PROCEDIMENTO (
        ID_PROCED INTEGER PRIMARY KEY AUTOINCREMENT,
        CD_PROCED TEXT UNIQUE NOT NULL,
        DS_PROCED TEXT NOT NULL,
        TP_CD_PROCED TEXT,
        DT_ATUALZ TEXT
    );
    """,

    # 5. PACIENTE
    """
    CREATE TABLE IF NOT EXISTS PACIENTE (
        ID_PACIEN INTEGER PRIMARY KEY AUTOINCREMENT,
        DT_ATUALZ_ORIGEM TEXT,
        NM_PACIEN TEXT NOT NULL,
        DT_NASC TEXT NOT NULL,
        DS_CNS TEXT UNIQUE,
        CD_CPF TEXT UNIQUE,
        NM_MAE TEXT,
        DS_RACA TEXT,
        DS_NACION TEXT,
        DS_TIPO_TEL1 TEXT,
        DS_TIPO_TEL2 TEXT,
        DS_TIPO_TEL3 TEXT,
        NU_TEL1 TEXT,
        NU_TEL2 TEXT,
        NU_TEL3 TEXT,
        DS_EMAIL TEXT,
        DS_TP_LOGRD TEXT,
        DS_LOGRD TEXT,
        NU_LOGRD TEXT,
        DS_COMPL TEXT,
        NM_BAIRRO TEXT,
        NM_MUNIC TEXT NOT NULL,
        SG_UF TEXT DEFAULT 'PE',
        CD_CEP TEXT,
        NU_IDADE INTEGER,
        DT_ATUALZ TEXT,
        FL_ANONIMIZADO TEXT DEFAULT '0',
        IN_SEXO TEXT,
        FL_OBITO INTEGER DEFAULT 0,
        NM_SOCIAL TEXT,
        DT_OBITO TEXT
    );
    """,
    
    # 6. ATENDIMENTO
    """
    CREATE TABLE IF NOT EXISTS ATENDIMENTO (
        ID_ATEND INTEGER PRIMARY KEY AUTOINCREMENT,
        ID_PACIEN INTEGER NOT NULL,
        DT_MOMENT_INIC TEXT NOT NULL,
        DT_MOMENT_FIM TEXT,
        ID_UNID INTEGER NOT NULL,
        DT_ATUALZ TEXT,
        ID_SISTEM_ORIGEM INTEGER,
        ID_PROFIS INTEGER,
        DS_TIPO_ATEND TEXT NOT NULL, -- 'A', 'E', 'I', 'APS'
        IN_SISTEM_ORIGEM INTEGER,
        DS_ESPECI TEXT,
        COMPLEMENTAR TEXT, -- JSON TEXT
        ID_CBO INTEGER,
        TP_FICHA TEXT,
        FOREIGN KEY (ID_PACIEN) REFERENCES PACIENTE (ID_PACIEN),
        FOREIGN KEY (ID_UNID) REFERENCES UNIDADE (ID_UNID),
        FOREIGN KEY (ID_PROFIS) REFERENCES PROFISSIONAL (ID_PROFIS),
        FOREIGN KEY (IN_SISTEM_ORIGEM) REFERENCES SISTEMA_ORIGEM (IN_SISTEM_ORIGEM)
    );
    """,
    
    # 7. ACOLHIMENTO
    """
    CREATE TABLE IF NOT EXISTS ACOLHIMENTO (
        ID_ACOLMT INTEGER PRIMARY KEY AUTOINCREMENT,
        ID_SISTEM_ORIGEM INTEGER,
        ID_PACIEN INTEGER NOT NULL,
        ID_ATEND INTEGER NOT NULL,
        DT_ACOLMT TEXT NOT NULL,
        DT_ATUALZ_ORIGEM TEXT,
        DT_FIM_ACOLMT TEXT,
        DS_COR_RISCO TEXT NOT NULL, -- VERMELHO, LARANJA, AMARELO, VERDE, AZUL
        DS_CLASSIF_RISCO TEXT NOT NULL, -- URGENTE, MUITO URGENTE, POUCO URGENTE, NÃO URGENTE
        DS_MEDICACAO TEXT,
        DS_SINTOMA TEXT,
        DS_RECOMENDACAO TEXT,
        DS_QUEIXA_PRINCIPAL TEXT,
        DS_INFOR_COMPL TEXT,
        DS_ESPECIALID TEXT,
        ID_PROFIS INTEGER,
        DT_ATUALZ TEXT,
        IN_SISTEM_ORIGEM INTEGER,
        FOREIGN KEY (ID_PACIEN) REFERENCES PACIENTE (ID_PACIEN),
        FOREIGN KEY (ID_ATEND) REFERENCES ATENDIMENTO (ID_ATEND),
        FOREIGN KEY (ID_PROFIS) REFERENCES PROFISSIONAL (ID_PROFIS),
        FOREIGN KEY (IN_SISTEM_ORIGEM) REFERENCES SISTEMA_ORIGEM (IN_SISTEM_ORIGEM)
    );
    """,
    
    # 8. DIAGNOSTICO (Catálogo Master)
    """
    CREATE TABLE IF NOT EXISTS DIAGNOSTICO (
        ID_DIAGN INTEGER PRIMARY KEY AUTOINCREMENT,
        CD_DIAG TEXT UNIQUE NOT NULL, -- CID-10 code (ex: 'E10.9')
        DS_DIAG TEXT NOT NULL,
        DT_ATUALZ TEXT,
        TP_CD_DIAG TEXT NOT NULL -- 'CID10' ou 'CIAP2'
    );
    """,
    
    # 9. ATEND_DIAGNOS (Relacionamento N:N entre Atendimento e Diagnóstico)
    """
    CREATE TABLE IF NOT EXISTS ATEND_DIAGNOS (
        ID_ATEND_DIAGNOS INTEGER PRIMARY KEY AUTOINCREMENT,
        FL_DIAGN_PRINCIPAL TEXT NOT NULL, -- '1' para principal, '0' para secundário
        ID_DIAGN INTEGER NOT NULL,
        ID_ATEND INTEGER NOT NULL,
        DT_ATUALZ TEXT,
        ID_SISTEM_ORIGEM INTEGER,
        DT_DIAGN TEXT NOT NULL,
        DS_OBS_DIAGN TEXT,
        IN_SISTEM_ORIGEM INTEGER,
        FOREIGN KEY (ID_DIAGN) REFERENCES DIAGNOSTICO (ID_DIAGN),
        FOREIGN KEY (ID_ATEND) REFERENCES ATENDIMENTO (ID_ATEND),
        FOREIGN KEY (IN_SISTEM_ORIGEM) REFERENCES SISTEMA_ORIGEM (IN_SISTEM_ORIGEM)
    );
    """,
    
    # 10. EXAME
    """
    CREATE TABLE IF NOT EXISTS EXAME (
        ID_EXAME INTEGER PRIMARY KEY AUTOINCREMENT,
        ID_UNID INTEGER NOT NULL,
        ID_PACIEN INTEGER NOT NULL,
        DT_ATUALZ_ORIGEM TEXT,
        DT_REALIZACAO TEXT NOT NULL,
        ID_PROFIS_EXEC INTEGER,
        ID_PROFIS_RESID INTEGER,
        ID_PROFIS_SOLIC INTEGER,
        DS_MODALIDADE TEXT,
        IN_SISTEM_ORIGEM INTEGER,
        ID_SISTEM_ORIGEM INTEGER,
        DT_ATUALZ TEXT,
        DS_SETOR_SOLIC TEXT,
        CD_SOLICITACAO INTEGER,
        ID_ATEND INTEGER NOT NULL,
        CD_ATEND INTEGER,
        ID_PROCED INTEGER,
        DS_EXAME TEXT,
        DT_SOLICITACAO TEXT,
        DT_LAUDO_LIBERADO TEXT,
        FOREIGN KEY (ID_UNID) REFERENCES UNIDADE (ID_UNID),
        FOREIGN KEY (ID_PACIEN) REFERENCES PACIENTE (ID_PACIEN),
        FOREIGN KEY (ID_ATEND) REFERENCES ATENDIMENTO (ID_ATEND),
        FOREIGN KEY (ID_PROFIS_EXEC) REFERENCES PROFISSIONAL (ID_PROFIS),
        FOREIGN KEY (ID_PROFIS_SOLIC) REFERENCES PROFISSIONAL (ID_PROFIS),
        FOREIGN KEY (ID_PROCED) REFERENCES PROCEDIMENTO (ID_PROCED),
        FOREIGN KEY (IN_SISTEM_ORIGEM) REFERENCES SISTEMA_ORIGEM (IN_SISTEM_ORIGEM)
    );
    """,
    
    # 11. RES_EXAME
    """
    CREATE TABLE IF NOT EXISTS RES_EXAME (
        ID_RES_EXAME INTEGER PRIMARY KEY AUTOINCREMENT,
        DT_RES_EXAME TEXT NOT NULL,
        ID_EXAME INTEGER NOT NULL,
        IN_SISTEM_ORIGEM INTEGER,
        ID_SISTEM_ORIGEM TEXT,
        DT_ATUALZ TEXT,
        CD_SOLICITACAO INTEGER,
        CD_VERSAO_RES_EXAME INTEGER,
        CD_CAMPOS_LAUDO INTEGER,
        DT_ATUALZ_ORIGEM TEXT,
        DS_RESULTADO TEXT NOT NULL, -- O resultado numérico do exame
        DS_CAMPO TEXT NOT NULL, -- Ex: 'HbA1c'
        ID_UNID INTEGER,
        FOREIGN KEY (ID_EXAME) REFERENCES EXAME (ID_EXAME),
        FOREIGN KEY (ID_UNID) REFERENCES UNIDADE (ID_UNID),
        FOREIGN KEY (IN_SISTEM_ORIGEM) REFERENCES SISTEMA_ORIGEM (IN_SISTEM_ORIGEM)
    );
    """,
    
    # 12. PRESCRICAO_MEDICAMENTO
    """
    CREATE TABLE IF NOT EXISTS PRESCRICAO_MEDICAMENTO (
        ID_PRESCR_MEDTO INTEGER PRIMARY KEY AUTOINCREMENT,
        DT_MEDTO_CRIAD_EM TEXT NOT NULL,
        CD_PRESCR_MEDTO INTEGER,
        DS_TIPO TEXT NOT NULL, -- 'principal', 'diluente', etc.
        DS_OBSERV_MEDTO TEXT,
        DS_VIA_ADMIN_MEDTO TEXT,
        NM_MEDTO TEXT NOT NULL,
        CD_MEDTO INTEGER,
        DT_INC TEXT NOT NULL,
        DT_FIM TEXT,
        DT_CRIACAO TEXT,
        CD_PRESC INTEGER,
        CD_ATEND_EMERG INTEGER,
        CD_ATEND INTEGER,
        IN_SISTEM_ORIGEM INTEGER,
        DT_ATUALZ TEXT,
        ID_PROFIS INTEGER,
        ID_ATEND INTEGER NOT NULL,
        DS_DOSE_MEDTO TEXT,
        ID_SISTEM_ORIGEM INTEGER,
        FOREIGN KEY (ID_ATEND) REFERENCES ATENDIMENTO (ID_ATEND),
        FOREIGN KEY (ID_PROFIS) REFERENCES PROFISSIONAL (ID_PROFIS),
        FOREIGN KEY (IN_SISTEM_ORIGEM) REFERENCES SISTEMA_ORIGEM (IN_SISTEM_ORIGEM)
    );
    """,
    
    # 13. IMUNIZACAO
    """
    CREATE TABLE IF NOT EXISTS IMUNIZACAO (
        ID_IMUNIZACAO INTEGER PRIMARY KEY AUTOINCREMENT,
        CD_CPF TEXT NOT NULL,
        DS_CNS TEXT,
        NM_UNID_IMUN TEXT,
        NM_MUNIC_IMUN TEXT,
        DT_ATUALZ_ORIGEM TEXT,
        DT_DELETED TEXT,
        DT_APLICACAO TEXT NOT NULL,
        CD_VACINA TEXT NOT NULL
    );
    """
]

DROP_STATEMENTS = [
    "DROP TABLE IF EXISTS IMUNIZACAO;",
    "DROP TABLE IF EXISTS PRESCRICAO_MEDICAMENTO;",
    "DROP TABLE IF EXISTS RES_EXAME;",
    "DROP TABLE IF EXISTS EXAME;",
    "DROP TABLE IF EXISTS ATEND_DIAGNOS;",
    "DROP TABLE IF EXISTS DIAGNOSTICO;",
    "DROP TABLE IF EXISTS ACOLHIMENTO;",
    "DROP TABLE IF EXISTS ATENDIMENTO;",
    "DROP TABLE IF EXISTS PACIENTE;",
    "DROP TABLE IF EXISTS PROCEDIMENTO;",
    "DROP TABLE IF EXISTS PROFISSIONAL;",
    "DROP TABLE IF EXISTS UNIDADE;",
    "DROP TABLE IF EXISTS SISTEMA_ORIGEM;"
]

def create_tables(conn: sqlite3.Connection):
    """Cria todas as tabelas no banco de dados SQLite, limpando antes se existirem."""
    cursor = conn.cursor()
    cursor.execute("PRAGMA foreign_keys = OFF;")
    for drop_stmt in DROP_STATEMENTS:
        cursor.execute(drop_stmt)
    for create_stmt in DDL_STATEMENTS:
        cursor.execute(create_stmt)
    cursor.execute("PRAGMA foreign_keys = ON;")
    conn.commit()
    print("[db_schema] Todas as tabelas foram limpas e criadas com sucesso.")

if __name__ == "__main__":
    # Teste de criação rápida local
    conn = sqlite3.connect("test_reds.db")
    create_tables(conn)
    conn.close()
    import os
    os.remove("test_reds.db")
